spring:
   thymeleaf:
       cache: false
       check-template-location: true       
   messages:
       basename: messages/messages
   application: 
        name: region-demo
        
region:
    resource:
        location:
            base: classpath:/static/images/
        